### ISSUE TITLE
Naming format isn't like the Python convention

### ISSUE THREAD

**Issue by rluvaton** [hurihuri123/pythonSession#5]
See Python [PEP 8][1].

## Functions
> Function names should be lowercase, with words separated by underscores as necessary to improve readability.
> 
> mixedCase is allowed only in contexts where that's already the prevailing style

## Variables

> Use the function naming rules:
> lowercase with words separated by underscores as necessary to improve readability.

## Example from your code of one from many 

https://github.com/hurihuri123/pythonSession/blob/d1943609697f479a4af17553fe68301a5c9e84c6/server/main.py#L39-L46

- `initServerSocket` function supposed to be `init_server_socket`
- `serverFD` variable in the class supposed to be `server_fd`

  [1]: http://www.python.org/dev/peps/pep-0008/

**Comment by hurihuri123** [comment]
I wasn't aware of the python conventions.
I will stick to them next time.
